# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('profile', models.IntegerField(choices=[(1, 'CEO'), (2, 'Senior Manager'), (3, 'Sales'), (4, 'Administrations, Financial, Operations'), (5, 'Marketing & PR'), (6, 'Consulting, Projet Management'), (7, 'Customer Care'), (8, 'Engineering, Systems, R&D'), (9, 'Training')])),
                ('working_time', models.IntegerField(choices=[(1, 'Fulltime'), (2, 'Partime')], default=1)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('gmail', 'Gmail'), ('hotmail', 'Hotmail'), ('other', 'Other')], max_length=6)),
                ('email_use', models.IntegerField(choices=[(1, 'Personal'), (2, 'Freelance'), (3, 'Enterprise')])),
                ('pref_language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='en', max_length=2)),
                ('timezone', models.CharField(choices=[('-12', 'GMT -12:00 Eniwetok, Kwajalein'), ('-11.0', 'GMT -11:00 Midway Island, Samoa'), ('-10.0', 'GMT -10:00 Hawaii'), ('-9.0', 'GMT -9:00 Alaska'), ('-8.0', 'GMT -8:00 Pacific Time (US & Canada)'), ('-7.0', 'GMT -7:00 Mountain Time (US & Canada)'), ('-6.0', 'GMT -6:00 Central Time (US & Canada, Mexico City'), ('-5.0', 'GMT -5:00 Eastern Time (US & Canada), Bogota, Lima'), ('-4.0', 'GMT -4:00 Atlantic Time (Canada), Caracas, La Paz'), ('-3.5', 'GMT -3:30 Newfoundland'), ('-3.0', 'GMT -3:00 Brazil, Buenos Aires, Georgetown'), ('-2.0', 'GMT -2:00 Mid-Atlantic'), ('-1.0', 'GMT -1:00 hour Azores, Cape Verde Islands'), ('0.0', 'GMT Western Europe Time, London, Lisbon, Casablanca'), ('1.0', 'GMT +1:00 Brussels, Copenhagen, Madrid, Paris'), ('2.0', 'GMT +2:00 Kaliningrad, South Africa'), ('3.0', 'GMT +3:00 Baghdad, Riyadh, Moscow, St. Petersburg'), ('3.5', 'GMT +3:30 Tehran'), ('4.0', 'GMT +4:00 Abu Dhabi, Muscat, Baku, Tbilisi'), ('4.5', 'GMT +4:30 Kabul'), ('5.0', 'GMT +5:00 Ekaterinburg, Islamabad, Karachi, Tashkent'), ('5.5', 'GMT +5:30 Bombay, Calcutta, Madras, New Delhi'), ('5.75', 'GMT +5:45 Kathmandu'), ('6.0', 'GMT +6:00 Almaty, Dhaka, Colombo'), ('7.0', 'GMT +7:00 Bangkok, Hanoi, Jakarta'), ('8.0', 'GMT +8:00 Beijing, Perth, Singapore, Hong Kong'), ('9.0', 'GMT +9:00 Tokyo, Seoul, Osaka, Sapporo, Yakutsk'), ('9.5', 'GMT +9:30 Adelaide, Darwin'), ('10.0', 'GMT +10:00 Eastern Australia, Guam, Vladivostok'), ('11.0', 'GMT +11:00 Magadan, Solomon Islands, New Caledonia'), ('12.0', 'GMT +12:00 Auckland, Wellington, Fiji, Kamchatka')], default='GMT', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
    ]
